name: retina_face
platform: "onnxruntime_onnx"
max_batch_size: 1


input: [
    {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCW
    dims:

    }
]

output: [
    {
    name: "output"
    data_type: TYPE_FP32
    dims: []


    }
]