name: telegram message
on: [push, issues]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ${{ github.actor }} created a new event:
            ${{ github.event_name }} event occurred.
            
            Repository: ${{ github.repository }}
            
            {% if github.event_name == 'push' %}
            Commit message: ${{ github.event.commits[0].message }}
            See changes: https://github.com/${{ github.repository }}/commit/${{ github.sha}}
            {% elif github.event_name == 'issues' %}
            Issue title: ${{ github.event.issue.title }}
            Issue body: ${{ github.event.issue.body }}
            See issue: https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}
            {% endif %}
